from typing import List

from .models import TopicDefinition


GLOBAL_ECON_KEYWORDS = [
    "economy",
    "경제",
    "inflation",
    "인플레이션",
    "물가",
    "deflation",
    "jobs",
    "고용",
    "payroll",
    "unemployment",
    "실업률",
    "fed",
    "연준",
    "기준금리",
    "interest rate",
    "mortgage",
    "모기지",
    "housing",
    "주택",
    "부동산",
    "consumer",
    "retail sales",
    "oil",
    "유가",
    "국제유가",
    "crude",
    "gas prices",
    "china",
    "중국",
    "growth target",
    "성장률",
    "경기부양",
    "trade",
    "무역",
    "tariff",
    "관세",
    "shipping",
    "해운",
    "data center",
    "데이터센터",
    "electricity",
    "전력",
    "power grid",
    "전력망",
    "semiconductor",
    "반도체",
    "earnings",
    "market",
    "환율",
    "수출",
    "pet",
    "grooming",
    "service",
    "airport",
    "budget",
    "shutdown",
    "defense",
    "factory",
    "worker",
    "반려동물",
    "펫",
    "서비스",
    "공항",
    "예산",
    "셧다운",
    "방산",
    "공장",
    "작업자",
    "폐로",
    "원전",
]

ANTI_KEYWORDS = [
    "celebrity",
    "oscars",
    "nfl",
    "nba",
    "mlb",
    "movie",
    "music",
    "gaming",
    "murder",
    "crime",
    "earthquake",
]


TOPIC_DEFINITIONS: List[TopicDefinition] = [
    TopicDefinition(
        slug="premium_pet_spending",
        label="반려동물 프리미엄 소비와 펫서비스 산업",
        news_queries=[
            "pet grooming spending luxury pet services",
        ],
        keywords=[
            "pet",
            "pets",
            "grooming",
            "pet services",
            "pet spa",
            "dog daycare",
            "반려동물",
            "펫",
            "미용",
            "펫서비스",
        ],
        why_now="가계 소비가 둔화돼도 특정 취향·돌봄 영역에는 지출이 몰리는 현상이 서비스 신산업의 성장으로 연결된다.",
        reader_fit="생활밀착형 소비 사례 하나로 서비스 물가, 프리미엄 소비, 신규 산업의 등장을 동시에 설명할 수 있다.",
        youtube_query="pet economy grooming luxury spending",
        korea_queries=[
            "반려동물 미용 프리미엄 소비",
        ],
        korea_relevance=1.24,
        story_bias=1.22,
        article_focus="사치 논란으로 끝내지 말고, 반려동물 미용·데이케어·보험 같은 세부 서비스가 어떻게 하나의 신산업으로 커지는지로 잡아야 한다.",
        reporting_points="객단가가 얼마나 올라왔는지, 구독·보험·호텔 같은 연관 매출이 붙는지, 경기 둔화 속에서도 왜 이 지출만 버티는지 확인하면 된다.",
    ),
    TopicDefinition(
        slug="public_service_bottlenecks",
        label="공항·공공서비스 병목과 예산 압박",
        news_queries=[
            "airport security lines shutdown budget staffing",
        ],
        keywords=[
            "airport",
            "security line",
            "tsa",
            "shutdown",
            "budget",
            "staffing",
            "wait time",
            "공항",
            "보안검색",
            "대기줄",
            "셧다운",
            "예산",
            "인력부족",
        ],
        why_now="예산과 인력 문제가 소비자 불편으로 바로 드러나는 순간, 재정 문제를 피부에 와 닿는 생활경제 기사로 만들 수 있다.",
        reader_fit="긴 보안검색 줄 같은 구체적 장면이 있어서 독자가 바로 이해하고, 뒤에 재정·행정의 큰 그림을 붙이기 쉽다.",
        youtube_query="airport security lines budget staffing",
        korea_queries=[
            "공항 보안검색 대기 예산 인력",
        ],
        korea_relevance=1.15,
        story_bias=1.22,
        article_focus="공항 팁이나 대기줄 불만으로 끝내지 말고, 왜 특정 공항으로 수요가 몰리는지와 허브공항 포화·노선 재편이 어떻게 맞물리는지로 써야 한다.",
        reporting_points="인천·김포 혼잡이 대체공항 수요를 키우는지, 슬롯·주차·보안검색 인력 중 어디가 병목인지, 여행객이 왜 청주 같은 선택지로 이동하는지 붙이면 된다.",
    ),
    TopicDefinition(
        slug="nuclear_decommissioning_workforce",
        label="폐로 현장 인력난과 원전 경제",
        news_queries=[
            "Fukushima decommissioning workforce nuclear economy",
        ],
        keywords=[
            "fukushima",
            "decommissioning",
            "worker",
            "cleanup",
            "nuclear plant",
            "폐로",
            "후쿠시마",
            "원전",
            "작업자",
            "현장",
        ],
        why_now="에너지 정책은 추상적으로 보이기 쉽지만 폐로 현장 노동, 지역경제, 안전비용으로 풀면 훨씬 구체적인 산업 기사로 바뀐다.",
        reader_fit="한 사람의 노동 이야기로 원전 산업, 지역경제, 세대교체까지 한 번에 설명할 수 있다.",
        youtube_query="Fukushima decommissioning workers nuclear economy",
        korea_queries=[
            "후쿠시마 폐로 작업 인력 원전 경제",
        ],
        korea_relevance=1.18,
        story_bias=1.25,
        article_focus="원전 찬반 일반론보다, 폐로 현장의 한 사람·한 작업 공정이 어떤 비용과 기술·인력 시장을 만드는지로 풀어야 한다.",
        reporting_points="누가 현장에 들어오는지, 훈련·안전장비·로봇 같은 연관 산업이 어떻게 붙는지, 지역경제와 세대교체까지 연결하면 기사가 선다.",
    ),
    TopicDefinition(
        slug="defense_export_supply_chain",
        label="방산 수출·재무장 공급망의 구체적 수혜",
        news_queries=[
            "Korea defense exports supply chain munitions",
        ],
        keywords=[
            "defense",
            "munitions",
            "missile",
            "artillery",
            "shipyard",
            "export order",
            "방산",
            "수주",
            "탄약",
            "미사일",
            "조선소",
            "수출",
            "공장",
        ],
        why_now="재무장 흐름은 거시 안보 기사처럼 보이지만 실제로는 공장 증설, 수주 잔고, 고용, 부품 공급망으로 읽을 때 경제 기사로 힘이 생긴다.",
        reader_fit="한국 독자가 강하게 반응하는 산업 소재이고, 개별 기업·공장·주문 흐름으로 쪼개기 쉬워 후속 기사 생산성이 높다.",
        youtube_query="Korea defense industry global market",
        korea_queries=[
            "한국 방산 수출 공급망",
        ],
        korea_relevance=1.32,
        story_bias=1.24,
        article_focus="안보 담론보다 공장 증설, 수주잔고, 부품 조달, 협력사 고용처럼 돈이 도는 장면으로 출발해야 한다.",
        reporting_points="어느 기업·공장이 실제 수혜를 보는지, 납기와 부품 병목이 어디인지, 한국 협력사와 지역 일자리로 어떻게 번지는지 붙이면 된다.",
    ),
    TopicDefinition(
        slug="us_jobs_fed",
        label="미국 고용 둔화와 연준 금리 딜레마",
        news_queries=[
            "US jobs report unemployment fed",
            "payrolls labor market interest rates",
        ],
        keywords=[
            "jobs",
            "payroll",
            "labor market",
            "unemployment",
            "fed",
            "연준",
            "rate cut",
            "wages",
            "hiring",
            "고용",
            "실업률",
            "비농업고용",
            "금리인하",
        ],
        why_now="고용이 식으면 경기 둔화 우려가 커지지만, 물가가 높은 상태면 금리 인하도 쉽지 않아 시장 해석이 크게 갈린다.",
        reader_fit="주식, 채권, 환율, 가계대출까지 동시에 흔드는 거시 핵심 변수라 경제 독자층의 체감도가 높다.",
        youtube_query="US jobs report Fed economy",
        korea_queries=[
            "미국 고용 연준 금리",
            "미국 비농업고용 실업률 연준",
        ],
        korea_relevance=1.08,
        story_bias=0.95,
        article_focus="Fed 미팅이나 CPI 숫자 자체보다, 이번 데이터가 연준의 금리인하 경로와 시장 기대를 어떻게 바꾸는지로 잡아야 한다.",
        reporting_points="점도표나 발언 톤이 달라지는지, 2년물 금리·달러·주택대출 금리에 어떤 신호가 번지는지, 한국 증시·환율에 어떤 파급이 있는지 붙이면 된다.",
    ),
    TopicDefinition(
        slug="oil_inflation",
        label="유가 급등과 인플레이션 재점화",
        news_queries=[
            "oil prices inflation middle east economy",
            "crude oil gasoline inflation growth",
        ],
        keywords=[
            "oil",
            "crude",
            "brent",
            "gas prices",
            "gas price",
            "diesel",
            "inflation",
            "hormuz",
            "energy prices",
            "유가",
            "국제유가",
            "수입물가",
            "휘발유",
            "휘발유값",
            "중동",
        ],
        why_now="유가 충격은 곧바로 물가, 물류비, 기업 마진, 소비심리로 전이되기 때문에 단기 뉴스 가치가 크다.",
        reader_fit="생활물가와 증시를 동시에 건드려 독자가 제목만 봐도 경제적 파급효과를 직관적으로 이해한다.",
        youtube_query="oil prices inflation economy",
        korea_queries=[
            "국제유가 물가 환율",
            "유가 상승 인플레이션 한국경제",
        ],
        korea_relevance=1.26,
        story_bias=0.96,
        article_focus="유가 일반론보다 주유소 가격, 항공 유류할증료, 운임, 원재료비처럼 실제로 체감되는 한 지점을 앞세워야 한다.",
        reporting_points="어느 가격표가 먼저 움직였는지, 소비자·항공사·물류업체 중 누가 먼저 맞는지, 그 변화가 물가와 금리 기대에 어떻게 번지는지 붙이면 된다.",
    ),
    TopicDefinition(
        slug="housing_mortgage",
        label="주택·모기지 금리의 변곡점",
        news_queries=[
            "mortgage rates housing affordability home sales",
            "housing market mortgage rates 6 percent",
        ],
        keywords=[
            "mortgage",
            "housing",
            "home sales",
            "homebuyer",
            "affordability",
            "30-year",
            "refinancing",
            "inventory",
            "모기지",
            "주택",
            "주택시장",
            "부동산",
        ],
        why_now="모기지 금리 변화는 단일 숫자처럼 보이지만 소비 여력, 건설 경기, 은행 대출까지 연결된다.",
        reader_fit="독자가 가장 쉽게 자신의 지갑과 연결시키는 분야라 클릭과 체류시간을 모두 기대할 수 있다.",
        youtube_query="mortgage rates housing market economy",
        korea_queries=[
            "주택담보대출 금리 부동산",
            "주택시장 금리 거래량",
        ],
        korea_relevance=1.05,
        story_bias=0.99,
        article_focus="금리 숫자보다 실제 차주나 매수자의 행동 변화, 거래량, 갈아타기 움직임 같은 장면으로 시작해야 한다.",
        reporting_points="첫 주택구매자·기존 차주·건설사 중 누가 먼저 반응하는지, 30년물 고정금리와 거래량이 어디서 변하는지 붙이면 된다.",
    ),
    TopicDefinition(
        slug="china_growth",
        label="중국 성장목표와 내수·부동산 회복성",
        news_queries=[
            "China growth target property consumption economy",
            "China domestic demand property slump trade economy",
        ],
        keywords=[
            "china",
            "growth target",
            "domestic demand",
            "property market",
            "consumption",
            "stimulus",
            "exports",
            "deflation",
            "중국",
            "성장목표",
            "부동산",
            "내수",
            "수출",
            "경기부양",
        ],
        why_now="중국의 성장 눈높이는 원자재, 수출, 반도체, 해운 등 한국과 글로벌 공급망 전반의 방향성을 바꾼다.",
        reader_fit="중국발 둔화 또는 부양은 한국 독자에게도 직접적인 수출·산업 뉴스로 번역되기 쉽다.",
        youtube_query="China economy growth target property market",
        korea_queries=[
            "중국 성장률 한국 수출",
            "중국 경기부양 부동산 반도체",
        ],
        korea_relevance=1.24,
        story_bias=0.95,
        article_focus="성장목표 숫자 하나보다 수출 급증, 할인 경쟁, 재고 조정처럼 현장에서 포착되는 한 단면으로 풀어야 한다.",
        reporting_points="어느 도시·업종·기업에서 주문이나 할인 압박이 나타나는지, 그 변화가 한국 수출·해운·반도체로 어떻게 이어지는지 붙이면 된다.",
    ),
    TopicDefinition(
        slug="ai_power_capex",
        label="AI 데이터센터 전력·설비투자 경쟁",
        news_queries=[
            "AI data center power grid electricity investment",
            "data centers electricity demand nuclear power AI",
        ],
        keywords=[
            "data center",
            "datacenter",
            "ai",
            "microgrid",
            "electricity",
            "power grid",
            "utilities",
            "nuclear",
            "utility bill",
            "power contract",
            "infrastructure",
            "capex",
            "데이터센터",
            "전력망",
            "변압기",
            "전력계약",
            "원전",
            "설비투자",
            "반도체",
        ],
        why_now="AI는 기술 기사로 소비되기 쉽지만 실제로는 전력, 건설, 반도체, 유틸리티 투자 스토리까지 묶이는 경제 주제다.",
        reader_fit="단순 신제품 뉴스보다 돈이 어디로 흐르는지 보여주는 주제라 경제면 독자에게 더 설득력이 있다.",
        youtube_query="AI data center power grid investment",
        korea_queries=[
            "AI 데이터센터 전력 반도체",
            "데이터센터 전력망 설비투자",
        ],
        korea_relevance=1.3,
        story_bias=1.15,
        article_focus="AI 일반론이 아니라 특정 데이터센터, 전력계약, 변압기, 유틸리티 투자 같은 한 건의 사례로 시작해야 한다.",
        reporting_points="누가 전력을 사들이는지, 송배전·변압기·가스·원전 중 어디에 돈이 붙는지, 어떤 기업이 수혜를 보는지 붙이면 된다.",
    ),
    TopicDefinition(
        slug="trade_tariffs",
        label="관세·무역 리쇼어링과 비용 압박",
        news_queries=[
            "tariffs trade costs manufacturing inflation",
            "trade policy reshoring supply chain costs",
        ],
        keywords=[
            "tariff",
            "trade",
            "import",
            "export",
            "reshoring",
            "manufacturing",
            "supply chain",
            "cost pressure",
            "관세",
            "무역",
            "공급망",
            "리쇼어링",
            "수출",
        ],
        why_now="관세는 정치 기사처럼 보이지만 실제로는 기업 비용과 소비자 물가에 즉시 반영되는 경제 이슈다.",
        reader_fit="정책 변화가 가격, 고용, 투자에 어떻게 전가되는지 설명하기 좋아 경제 기사 소재로 재가공하기 쉽다.",
        youtube_query="tariffs trade costs inflation economy",
        korea_queries=[
            "관세 무역 한국 수출",
            "공급망 리쇼어링 비용 압박",
        ],
        korea_relevance=1.18,
        story_bias=0.97,
        article_focus="정치 뉴스처럼 다루지 말고, 법원 판단이나 관세 조정이 기업의 가격·재고·조달 전략을 어떻게 바꾸는지로 기사화해야 한다.",
        reporting_points="자동차·철강·반도체 중 어느 업종이 먼저 가격 인상이나 선적 조정을 하는지, 한국 수출기업 비용에 어떻게 전가되는지 붙이면 된다.",
    ),
]
