from typing import List

from .models import TopicDefinition


GLOBAL_ECON_KEYWORDS = [
    "economy",
    "경제",
    "inflation",
    "인플레이션",
    "물가",
    "deflation",
    "jobs",
    "고용",
    "payroll",
    "unemployment",
    "실업률",
    "fed",
    "연준",
    "기준금리",
    "interest rate",
    "mortgage",
    "모기지",
    "housing",
    "주택",
    "부동산",
    "consumer",
    "retail sales",
    "oil",
    "유가",
    "국제유가",
    "crude",
    "gas prices",
    "china",
    "중국",
    "growth target",
    "성장률",
    "경기부양",
    "trade",
    "무역",
    "tariff",
    "관세",
    "shipping",
    "해운",
    "data center",
    "데이터센터",
    "electricity",
    "전력",
    "power grid",
    "전력망",
    "semiconductor",
    "반도체",
    "earnings",
    "market",
    "환율",
    "수출",
]

ANTI_KEYWORDS = [
    "celebrity",
    "oscars",
    "nfl",
    "nba",
    "mlb",
    "movie",
    "music",
    "gaming",
    "murder",
    "crime",
    "earthquake",
]


TOPIC_DEFINITIONS: List[TopicDefinition] = [
    TopicDefinition(
        slug="us_jobs_fed",
        label="미국 고용 둔화와 연준 금리 딜레마",
        news_queries=[
            "US jobs report unemployment fed",
            "payrolls labor market interest rates",
        ],
        keywords=[
            "jobs",
            "payroll",
            "labor market",
            "unemployment",
            "fed",
            "연준",
            "rate cut",
            "wages",
            "hiring",
            "고용",
            "실업률",
            "비농업고용",
            "금리인하",
        ],
        why_now="고용이 식으면 경기 둔화 우려가 커지지만, 물가가 높은 상태면 금리 인하도 쉽지 않아 시장 해석이 크게 갈린다.",
        reader_fit="주식, 채권, 환율, 가계대출까지 동시에 흔드는 거시 핵심 변수라 경제 독자층의 체감도가 높다.",
        youtube_query="US jobs report Fed economy",
        korea_queries=[
            "미국 고용 연준 금리",
            "미국 비농업고용 실업률 연준",
        ],
        korea_relevance=1.08,
    ),
    TopicDefinition(
        slug="oil_inflation",
        label="유가 급등과 인플레이션 재점화",
        news_queries=[
            "oil prices inflation middle east economy",
            "crude oil gasoline inflation growth",
        ],
        keywords=[
            "oil",
            "crude",
            "brent",
            "gas prices",
            "diesel",
            "inflation",
            "hormuz",
            "energy prices",
            "유가",
            "국제유가",
            "수입물가",
            "휘발유",
            "중동",
        ],
        why_now="유가 충격은 곧바로 물가, 물류비, 기업 마진, 소비심리로 전이되기 때문에 단기 뉴스 가치가 크다.",
        reader_fit="생활물가와 증시를 동시에 건드려 독자가 제목만 봐도 경제적 파급효과를 직관적으로 이해한다.",
        youtube_query="oil prices inflation economy",
        korea_queries=[
            "국제유가 물가 환율",
            "유가 상승 인플레이션 한국경제",
        ],
        korea_relevance=1.26,
    ),
    TopicDefinition(
        slug="housing_mortgage",
        label="주택·모기지 금리의 변곡점",
        news_queries=[
            "mortgage rates housing affordability home sales",
            "housing market mortgage rates 6 percent",
        ],
        keywords=[
            "mortgage",
            "housing",
            "home sales",
            "homebuyer",
            "affordability",
            "30-year",
            "refinancing",
            "inventory",
            "모기지",
            "주택",
            "주택시장",
            "부동산",
        ],
        why_now="모기지 금리 변화는 단일 숫자처럼 보이지만 소비 여력, 건설 경기, 은행 대출까지 연결된다.",
        reader_fit="독자가 가장 쉽게 자신의 지갑과 연결시키는 분야라 클릭과 체류시간을 모두 기대할 수 있다.",
        youtube_query="mortgage rates housing market economy",
        korea_queries=[
            "주택담보대출 금리 부동산",
            "주택시장 금리 거래량",
        ],
        korea_relevance=1.05,
    ),
    TopicDefinition(
        slug="china_growth",
        label="중국 성장목표와 내수·부동산 회복성",
        news_queries=[
            "China growth target property consumption economy",
            "China domestic demand property slump trade economy",
        ],
        keywords=[
            "china",
            "growth target",
            "domestic demand",
            "property market",
            "consumption",
            "stimulus",
            "exports",
            "deflation",
            "중국",
            "성장목표",
            "부동산",
            "내수",
            "수출",
            "경기부양",
        ],
        why_now="중국의 성장 눈높이는 원자재, 수출, 반도체, 해운 등 한국과 글로벌 공급망 전반의 방향성을 바꾼다.",
        reader_fit="중국발 둔화 또는 부양은 한국 독자에게도 직접적인 수출·산업 뉴스로 번역되기 쉽다.",
        youtube_query="China economy growth target property market",
        korea_queries=[
            "중국 성장률 한국 수출",
            "중국 경기부양 부동산 반도체",
        ],
        korea_relevance=1.24,
    ),
    TopicDefinition(
        slug="ai_power_capex",
        label="AI 데이터센터 전력·설비투자 경쟁",
        news_queries=[
            "AI data center power grid electricity investment",
            "data centers electricity demand nuclear power AI",
        ],
        keywords=[
            "data center",
            "datacenter",
            "ai",
            "electricity",
            "power grid",
            "nuclear",
            "utility bill",
            "infrastructure",
            "capex",
            "ai",
            "데이터센터",
            "전력망",
            "변압기",
            "원전",
            "설비투자",
            "반도체",
        ],
        why_now="AI는 기술 기사로 소비되기 쉽지만 실제로는 전력, 건설, 반도체, 유틸리티 투자 스토리까지 묶이는 경제 주제다.",
        reader_fit="단순 신제품 뉴스보다 돈이 어디로 흐르는지 보여주는 주제라 경제면 독자에게 더 설득력이 있다.",
        youtube_query="AI data center power grid investment",
        korea_queries=[
            "AI 데이터센터 전력 반도체",
            "데이터센터 전력망 설비투자",
        ],
        korea_relevance=1.3,
    ),
    TopicDefinition(
        slug="trade_tariffs",
        label="관세·무역 리쇼어링과 비용 압박",
        news_queries=[
            "tariffs trade costs manufacturing inflation",
            "trade policy reshoring supply chain costs",
        ],
        keywords=[
            "tariff",
            "trade",
            "import",
            "export",
            "reshoring",
            "manufacturing",
            "supply chain",
            "cost pressure",
            "관세",
            "무역",
            "공급망",
            "리쇼어링",
            "수출",
        ],
        why_now="관세는 정치 기사처럼 보이지만 실제로는 기업 비용과 소비자 물가에 즉시 반영되는 경제 이슈다.",
        reader_fit="정책 변화가 가격, 고용, 투자에 어떻게 전가되는지 설명하기 좋아 경제 기사 소재로 재가공하기 쉽다.",
        youtube_query="tariffs trade costs inflation economy",
        korea_queries=[
            "관세 무역 한국 수출",
            "공급망 리쇼어링 비용 압박",
        ],
        korea_relevance=1.18,
    ),
]
